#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# NOTE: take care to keep the syntax bash compatible
#

# application information
meta_name="oib-tafel"
meta_version="0.0.1"

# webserver port
port=9090

# log files
web_logfile="var/access.log"
app_logfile="var/application.log"
sql_logfile="var/sql.log"

# session defaults
session_salt="6ac0e40b-af3a-40d2-aa6c-c6ba08bf8a6c"
session_timeout=86400 #24 * 60 * 60, # 24 hours   in seconds
session_dir='var'
session_dir_prefix="session_"
# session_name="framework" # autogenerated from meta["name"]
session_cookie_domain=None
session_ignore_expiry=True
session_ignore_change_ip=False
session_expired_message='Session expired'

user_db="etc/user.db"

